FROM openjdk:14.0.2-slim

RUN apt update && apt install -y wkhtmltopdf fonts-noto-cjk/stable && apt clean

ARG JAR
ARG PORT

WORKDIR /application
COPY ${JAR} /application/app.jar

EXPOSE ${PORT}
CMD [ "java", "-jar", "-Duser.timezone=UTC", "/application/app.jar"]]
